### ISSUE TITLE
TypeError: iter() returned non-iterator of type 'SearchResultPages'

### ISSUE THREAD

**Issue by attackjoker11** [fs0c131y/AadhaarSearchEngine#1]
```
2018-03-20 08:04:47 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: AadhaarSearchEngine)
2018-03-20 08:04:47 [scrapy.utils.log] INFO: Versions: lxml 4.2.0.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.4 (default, Mar  9 2018, 23:15:03) - [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.2, Platform Darwin-17.4.0-x86_64-i386-64bit
2018-03-20 08:04:47 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'AadhaarSearchEngine', 'DEPTH_LIMIT': 1, 'DOWNLOAD_DELAY': 30, 'NEWSPIDER_MODULE': 'AadhaarSearchEngine.spiders', 'SPIDER_MODULES': ['AadhaarSearchEngine.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'}
2018-03-20 08:04:47 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2018-03-20 08:04:47 [twisted] CRITICAL: Unhandled error in Deferred:

2018-03-20 08:04:47 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiders/__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/ammu/AadhaarSearchEngine/AadhaarSearchEngine/spiders/AadhaarSpider.py", line 24, in __init__
    for url in page_urls:
TypeError: iter() returned non-iterator of type 'SearchResultPages'
```

**Comment by djsan15** [comment]
Still getting this error. Any fix?

**Comment by arnav-deep** [comment]
Still getting this error
